### ISSUE TITLE
Android上显示20多个平台，ios上只显示配置的微信平台

### ISSUE THREAD

**Issue by VFiee** [MobClub/ShareSDK-For-Flutter#12]
问题描述：
1、项目里面只配置了微信朋友圈和微信会话，在ios上显示正常，在android上显示很多平台，
2、android上显示很多平台，点击朋友圈或者微信会话分享时，先弹出进入后台，然后弹出分享失败。QQ和QQ空间正常（虽然没有配置）

android上menu菜单
![WechatIMG15](https://user-images.githubusercontent.com/42051272/55768718-8befc000-5ab0-11e9-8645-592243fa51ec.jpeg)

mobsdk.gradle配置
![161554776473_ pic](https://user-images.githubusercontent.com/42051272/55768887-35cf4c80-5ab1-11e9-9ae7-bb7564e2ee7c.jpg)

封装的微信分享逻辑（只有微信分享）
![171554776550_ pic_hd](https://user-images.githubusercontent.com/42051272/55768941-7038e980-5ab1-11e9-99cf-14576f251e30.jpg)

**Comment by VFiee** [comment]
@DangerousDON 可否咨询您关于Android端怎么调取微信的一些问题（sharesdk）

**Comment by hanandjun** [comment]
附议

**Comment by moblarry** [comment]
Mobgradle之前的版本默认都集成，下周会上个新的版本，需要的平台自己配置即可，重新编译即可
