### ISSUE TITLE
await ShareSDK.regist(register) 报错

### ISSUE THREAD

**Issue by dengsgo** [MobClub/ShareSDK-For-Flutter#2]
![qq 20190115113849](https://user-images.githubusercontent.com/7929002/51157316-56c14080-18ba-11e9-92e0-96cc8e621ba9.png)

追踪源代码，发现你们没有实现这个方法???  

![qq 20190115114141](https://user-images.githubusercontent.com/7929002/51157351-8a9c6600-18ba-11e9-8711-6fe670360568.png)

**Comment by 1019238091** [comment]
这个方法并不会影响到现有功能的使用，后面会更新实现这个方法。

**Comment by dengsgo** [comment]
好的 ...
