### ISSUE TITLE
gradle配置

### ISSUE THREAD

**Issue by yinzhiqun** [MobClub/ShareSDK-For-Flutter#24]
配置完之后，查看打包的apk文件，发现有两个Mob-AppSercet，其中有一个拼写错误的，是我自己申请的，另一个什么情况？？？另外说一点，flutter版本集成文档真的不行，乱七八糟，跟示例代码都不一样
![image](https://user-images.githubusercontent.com/24405130/61921285-3a037500-af8f-11e9-89a7-d6ac687e24b7.png)

**Comment by niugengyun** [comment]
听我的 弃坑吧

**Comment by yinzhiqun** [comment]
> 听我的 弃坑吧

我已经自己写好插件了汗 流汗

**Comment by niugengyun** [comment]
> > 听我的 弃坑吧
> 
> 我已经自己写好插件了汗 流汗

swift不能编译
