### ISSUE TITLE
你们的这个微信分享掉不起来啊

### ISSUE THREAD

**Issue by 2534290808** [MobClub/ShareSDK-For-Flutter#26]
你们的这个微信分享掉不起来啊，有没mobsdk稳定版啊

**Comment by DangerousDON** [comment]
是安卓的还是ios的



刘芳丽 Lisa Liu
MobTech 技术支持 

E • liufl@yoozoo.com
M • +86 18824179331

FLOOR 4,SOUTH BUILDING B3,PUTIAN INFORMATION INDUSTRIAL PARK,700 YISHAN RD,XUHUI DISTRICT,SHANGHAI,CHINA
上海市徐汇区宜山路700号普天信息产业园B3南栋4层


本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！
This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks.

 
发件人： 黎明
发送时间： 2019-08-06 20:54
收件人： MobClub/ShareSDK-For-Flutter
抄送： Subscribed
主题： [MobClub/ShareSDK-For-Flutter] 你们的这个微信分享掉不起来啊 (#26)
你们的这个微信分享掉不起来啊，有没mobsdk稳定版啊

**Comment by 2534290808** [comment]
这个是android的

**Comment by DangerousDON** [comment]
你加一下官方的技术扣哦4006852216，联系下技术支持！



刘芳丽 Lisa Liu
MobTech 技术支持 

E • liufl@yoozoo.com
M • +86 18824179331

FLOOR 4,SOUTH BUILDING B3,PUTIAN INFORMATION INDUSTRIAL PARK,700 YISHAN RD,XUHUI DISTRICT,SHANGHAI,CHINA
上海市徐汇区宜山路700号普天信息产业园B3南栋4层


本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！
This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks.

 
发件人： 黎明
发送时间： 2019-08-07 10:00
收件人： MobClub/ShareSDK-For-Flutter
抄送： Donel Chan; Comment
主题： Re: [MobClub/ShareSDK-For-Flutter] 你们的这个微信分享掉不起来啊 (#26)
这个是android的

**Comment by 2534290808** [comment]
弃坑了，走了，祝你好运
