### ISSUE TITLE
sharesdk能否开发一个支持androidX的版本

### ISSUE THREAD

**Issue by VFiee** [MobClub/ShareSDK-For-Flutter#33]
升级为androidX是版本趋势，希望sharesdk团队能考虑一下将sharesdk的flutter版本支持androidX。

**Comment by moblarry** [comment]
> 升级为androidX是版本趋势，希望sharesdk团队能考虑一下将sharesdk的flutter版本支持androidX。

原生的已完成适配，我们会在最近一到两周内更新Flutter的插件，介时就会支持androidX
