### ISSUE TITLE
AndroidManifest中需要加入配置  tools:replace="android:name" 出错

### ISSUE THREAD

**Issue by iperfectapp** [MobClub/ShareSDK-For-Flutter#41]
![image](https://user-images.githubusercontent.com/3021764/66994542-005e8800-f100-11e9-985a-8a3876b2b606.png)
![image](https://user-images.githubusercontent.com/3021764/66994573-0c4a4a00-f100-11e9-9630-217b62e8c265.png)
![image](https://user-images.githubusercontent.com/3021764/66994628-208e4700-f100-11e9-86ad-2a27465d1a9d.png)

**Comment by onewkl** [comment]
咋解决呢
