### ISSUE TITLE
无法跳转到小程序

### ISSUE THREAD

**Issue by wiseideal** [MobClub/ShareSDK-For-Flutter#47]
可以做分享 但是无法分享小程序 提示universal link验证失败 换回官方1861一切正常

**Comment by wiseideal** [comment]
已经解决了  之前引入了libc++库 去除以后就可以了

**Comment by yanqiqi1996** [comment]
@wiseideal  你好，我也遇到这个问题。  我想问一下，分享小程序必须要配universal link 吗 url Schema不行吗。该怎么解决求解答
