### ISSUE TITLE
如何去掉不需要的平台？如何解决jar包冲突？

### ISSUE THREAD

**Issue by zcweng** [MobClub/ShareSDK-For-Flutter#5]
1.如何去掉不需要的平台？
  android展开后，发现打包了每个渠道
  该如何配置gradle文件

2.如何解决jar包冲突？
   项目使用了微博的其他功能，和你们的冲突了，不能编译

**Comment by 1019238091** [comment]
您好，十分荣幸您使用我们的产品。现在回答您第一个问题，您可以直接在展开后的目录结构下，找到MobSDK.gradle这个文件来直接配置您的gradle文件。您可以去掉不需要的平台，留下您需要的平台。在您需要的平台下面填入自己申请的key，然后重新拉取即可。详情可以参见 http://wiki.mob.com/sdk-share-android-3-0-0/
您的第二个问题欢迎您访问我们的官网http://www.mob.com/ 联系我们的技术支持，来具体指导您解决此问题。

**Comment by moblarry** [comment]
> 1.如何去掉不需要的平台？
> android展开后，发现打包了每个渠道
> 该如何配置gradle文件
> 
> 2.如何解决jar包冲突？
> 项目使用了微博的其他功能，和你们的冲突了，不能编译

Android的第三方平台已经做了优化，下周会上个新的版本，可以自己手动配置自己想要的平台，方便快捷

**Comment by zcweng** [comment]
好的，谢谢
