### ISSUE TITLE
升级ShareSDK 1.2.0后  隐私协议点同意APP会崩溃你妈妈知道吗  🤗

### ISSUE THREAD

**Issue by WangPe1n** [MobClub/ShareSDK-For-Flutter#57]
<img width="922" alt="WeChatce30e6fbe2c76152d790ff3c8d6bf7a9" src="https://user-images.githubusercontent.com/22020970/74582369-c2159e80-4ff5-11ea-81cb-fd4641c539fd.png">

**Comment by deboLing** [comment]
就是啊、他们技术支持也是气死个人、喊我自己调试、插件内部抛出的异常，让我如何去调试，宝宝心里苦

**Comment by moblarry** [comment]
您好，新版本已经修复，给您带来不便实在抱歉

**Comment by bossbaba** [comment]
您提个issue还需要问候一下人家亲属？我回复一下是不是也要问候一下您的亲属？插件出错就出错，人家给你开源出来就是为了给你提供便利，要是人人都像你这样，那还有个毛线的插件。
