### ISSUE TITLE
集成sdk后打包出错

### ISSUE THREAD

**Issue by a251115100** [MobClub/ShareSDK-For-Flutter#62]
Execution failed for task ':sharesdk_plugin:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /Users/godlike/.gradle/caches/transforms-2/files-2.1/03d9f98dc6ba9e8169e3b61a24f93127/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

**Comment by huntrist** [comment]
flutter 1.12.13+hotfix.9
存在该问题

**Comment by a251115100** [comment]
已解决,谢谢

**Comment by pslxx** [comment]
@a251115100 怎么解决啊
