### ISSUE TITLE
设备未安装

### ISSUE THREAD

**Issue by VFiee** [MobClub/ShareSDK-For-Flutter#9]
![IMG_2471](https://user-images.githubusercontent.com/42051272/55467798-9a635500-5634-11e9-88d6-61bde8421fcd.PNG)

点击分享的时候报错如下~（微信客户端已经安装了）

**Comment by VFiee** [comment]
@DangerousDON [捂脸][捂脸][捂脸]这个问题能帮忙看看么

**Comment by DangerousDON** [comment]
您如果要分享微信,QQ这些平台，是需要在真机上安装微信，QQ等客户端的，不然分享菜单上不会显示这些平台，也不会分享的，就会提示这个错误信息，没有有效平台显示，其二还需要配置对应的平台的白名单等信息，不然即使安装也可能检测不到的。



刘芳丽
MOB云事业部 技术支持 
YOOZOO GAMES 游族网络

E • liufl@yoozoo.com
M • +86 18824179331
T • +86 21 3367 6512
F • +86 21 3367 6520

YOOZOO MANSION,BUILDING 2,711 YISHAN RD.,XUHUI DISTRICT,SHANGHAI,CHINA 上海市徐汇区宜山路711号2号楼游族大厦 2200233




本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！
This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks.

 
发件人： Vyron
发送时间： 2019-04-03 16:54
收件人： MobClub/ShareSDK-For-Flutter
抄送： Subscribed
主题： [MobClub/ShareSDK-For-Flutter] 设备未安装 (#9)

点击分享的时候报错如下~

**Comment by 2534290808** [comment]
最好是提供判断客户端是否安装的方法（android和IOS）

**Comment by DangerousDON** [comment]
已经加了判断是否安装客户端的方法，更新到最新版本就行



刘芳丽 Lisa Liu
MobTech 技术支持 

E • liufl@yoozoo.com
M • +86 18824179331

FLOOR 4,SOUTH BUILDING B3,PUTIAN INFORMATION INDUSTRIAL PARK,700 YISHAN RD,XUHUI DISTRICT,SHANGHAI,CHINA
上海市徐汇区宜山路700号普天信息产业园B3南栋4层


本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！
This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks.

 
发件人： 黎明
发送时间： 2019-08-07 10:02
收件人： MobClub/ShareSDK-For-Flutter
抄送： Donel Chan; Mention
主题： Re: [MobClub/ShareSDK-For-Flutter] 设备未安装 (#9)
最好是提供判断客户端是否安装的方法（android和IOS）

**Comment by 2534290808** [comment]
上面显示知识IOS支持的，android不支持

**Comment by DangerousDON** [comment]
是的，ios的已经支持了，安卓的下个版本会加上哈！



刘芳丽 Lisa Liu
MobTech 技术支持 

E • liufl@yoozoo.com
M • +86 18824179331

FLOOR 4,SOUTH BUILDING B3,PUTIAN INFORMATION INDUSTRIAL PARK,700 YISHAN RD,XUHUI DISTRICT,SHANGHAI,CHINA
上海市徐汇区宜山路700号普天信息产业园B3南栋4层


本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！
This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks.

 
发件人： 黎明
发送时间： 2019-08-07 10:11
收件人： MobClub/ShareSDK-For-Flutter
抄送： Donel Chan; Mention
主题： Re: [MobClub/ShareSDK-For-Flutter] 设备未安装 (#9)
上面显示知识IOS支持的，android不支持

**Comment by 2534290808** [comment]
哦，好的
