### ISSUE TITLE
集成后 iOS能运行  安卓一直报错 

### ISSUE THREAD

**Issue by guoshengboy** [MobClub/ShareSDK-For-Flutter#95]
/Users/SMG/Desktop/dev/flutter/.pub-cache/hosted/pub.flutter-io.cn/sharesdk_plugin-1.3.2/android/src/main/java/com/yoozoo/sharesdk/SharesdkPlugin.java:269: 错误: 找不到符号
      MobSDK.getPrivacyPolicyAsync(Type, new PrivacyPolicy.OnPolicyListener() {
            ^
  符号:   方法 getPrivacyPolicyAsync(int,<匿名OnPolicyListener>)
  位置: 类 MobSDK

**Comment by LPKgreenhand** [comment]
https://github.com/MobClub/ShareSDK-For-Flutter/issues/93#issuecomment-1124585407
参考这位的方案

**Comment by guoshengboy** [comment]
> [#93 (comment)](https://github.com/MobClub/ShareSDK-For-Flutter/issues/93#issuecomment-1124585407) 参考这位的方案

好的 我看看

**Comment by wikiwikiki** [comment]
> [#93 (comment)](https://github.com/MobClub/ShareSDK-For-Flutter/issues/93#issuecomment-1124585407) 参考这位的方案

hello 我遇到了同样的问题，已经添加了两个属性依然不可以，还有什么排查方式吗

**Comment by wikiwikiki** [comment]
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/45203334/188068335-227e2954-d393-4d4c-9645-45f1276307a0.png">
